<?php
/** @var \Magento\Framework\View\Element\Template $block */
$jsLayout = $block->getData('jsLayout');
?>
<div id="exit-intent-popup-wrapper"
     data-bind="scope: 'exit-intent-popup'"
     aria-live="polite"
     aria-atomic="true">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
{
    "#exit-intent-popup-wrapper": {
        "Magento_Ui/js/core/app": <?= /* @noEscape */ json_encode($jsLayout) ?>
    }
}
</script>
